#!/usr/bin/env python3
"""Fetch the dashboard's latin-subset woff2 fonts from Google Fonts and self-host them.

One-time/regenerate helper. Queries the Google Fonts CSS2 API with a desktop
User-Agent (so it returns woff2 URLs), downloads only the `latin` subset for the
weights the dashboard CSS uses, saves them under static/fonts/, and prints the
matching @font-face rules to stdout (paste/prepend into style.css).

Run from repo root:  python scripts/fetch_fonts.py
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

DEST = Path(__file__).resolve().parent.parent / "src" / "dayctl" / "server" / "static" / "fonts"
URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Bricolage+Grotesque:wght@500;600;700"
    "&family=Geist:wght@300;400;500;600"
    "&family=JetBrains+Mono:wght@400;500;600"
    "&display=swap"
)
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"}

BLOCK_RE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{([^}]*)\}", re.S)
FAMILY_RE = re.compile(r"font-family:\s*'([^']+)'")
WEIGHT_RE = re.compile(r"font-weight:\s*(\d+)")
SRC_RE = re.compile(r"url\((https://[^)]+\.woff2)\)")


def main() -> int:
    DEST.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(URL, headers=UA)
    css = urllib.request.urlopen(req, timeout=30).read().decode("utf-8")

    faces: list[tuple[str, str, str]] = []  # (family, weight, filename)
    seen: set[str] = set()
    for subset, body in BLOCK_RE.findall(css):
        if subset != "latin":
            continue
        fam = FAMILY_RE.search(body)
        wght = WEIGHT_RE.search(body)
        src = SRC_RE.search(body)
        if not (fam and wght and src):
            continue
        family, weight, url = fam.group(1), wght.group(1), src.group(1)
        fname = f"{family.replace(' ', '')}-{weight}.woff2"
        if fname in seen:
            continue
        seen.add(fname)
        urllib.request.urlretrieve(url, DEST / fname)
        faces.append((family, weight, fname))
        print(f"saved {fname}", file=sys.stderr)

    print("\n/* self-hosted fonts (generated by scripts/fetch_fonts.py) */")
    for family, weight, fname in faces:
        print(
            f'@font-face {{ font-family:"{family}"; font-style:normal; font-weight:{weight}; '
            f'font-display:swap; src:url("/static/fonts/{fname}") format("woff2"); }}'
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
